"""
Core components for the Video Processing Pipeline
"""

from .pipeline import PipelineOrchestrator
from .config import ConfigurationManager
from .logging import setup_logging, get_logger
from .exceptions import (
    PipelineError,
    ConfigurationError,
    ProcessingError,
    ValidationError,
    TransientError
)
from .media_preparation import (
    MediaPreparationEngine,
    MediaValidator,
    MediaHealthChecker,
    MediaPreparationPipeline,
    AudioFile,
    ValidationResult
)
from .models import ClipObject, ClipAsset, ClipStatus
from .clip_registry import ClipRegistry
from .feed_generator import (
    FeedGenerator,
    RSSFeed,
    XMLSitemap,
    FeedCache,
    create_feed_generator,
    validate_feed_xml
)
from .platform_profiles import (
    PlatformProfile,
    PlatformProfileLoader,
    MediaSpecValidator,
    VideoSpecs,
    AudioSpecs,
    MetadataSpecs,
    create_default_profiles_config,
    save_default_profiles_config
)
from .media_normalizer import (
    MediaNormalizationPipeline,
    VideoTranscoder,
    AudioNormalizer,
    ThumbnailGenerator,
    CaptionProcessor,
    MediaProber,
    NormalizationJob,
    NormalizationResult,
    create_normalization_pipeline
)
from .social_generator import (
    SocialGenerator,
    PlatformMetadataFormatter,
    SocialPackageValidator,
    SocialGenerationJob,
    SocialGenerationResult,
    create_social_generator
)

from .social_queue_manager import (
    SocialQueueManager,
    SocialQueue,
    QueueItem,
    QueueItemStatus,
    SchedulingStrategy,
    SchedulingConfig,
    create_social_queue_manager,
    create_scheduling_config
)
from .publishing_system import (
    PublishingSystem,
    PublishingConfig,
    WorkflowResult,
    WorkflowStage,
    create_publishing_system,
    create_default_config,
    load_config_from_file
)
from .publishing_config import (
    ConfigurationManager,
    Environment,
    FeatureFlag,
    EnvironmentConfig,
    IntegrationConfig,
    SecretConfig,
    create_configuration_manager,
    create_default_environment_configs,
    setup_default_config_files
)
from .workflow_orchestrator import (
    WorkflowOrchestrator,
    WorkflowPhase,
    WorkflowMetrics,
    WorkflowReport,
    create_workflow_orchestrator,
    create_workflow_orchestrator_from_config
)
from .compliance_validator import (
    ComplianceValidator,
    RightsValidator,
    ContentPolicyValidator,
    AccessibilityValidator,
    ComplianceReport,
    ComplianceViolation,
    ContentPolicyRule,
    ContentRating,
    ComplianceLevel,
    create_compliance_validator
)
from .deployment_pipeline import (
    DeploymentPipeline,
    StagingDeployment,
    ProductionDeployment,
    ValidationGateSystem,
    DeploymentConfig,
    DeploymentResult,
    DeploymentStatus,
    Environment,
    ValidationGateType,
    ValidationGateResult,
    ValidationReport,
    DeploymentHistory,
    ContentCounts,
    create_deployment_pipeline,
    create_staging_deployment,
    create_production_deployment,
    create_validation_gate_system,
    create_zero_tolerance_config,
    create_lenient_config,
    validate_deployment_config
)
from .platform_integrator import (
    PlatformIntegrator,
    SearchEngineIntegrator,
    SocialPostingQueue,
    PlatformAPIIntegrator,
    OptionalPlatformIntegrator,
    PlatformCredentials,
    SubmissionResult,
    VerificationResult,
    QueueItem,
    PostingReceipt,
    QueueResult,
    PostResult,
    PlatformType,
    SubmissionStatus,
    ErrorClassification,
    GoogleSearchConsoleClient,
    BingWebmasterToolsClient,
    YouTubeAPIClient,
    InstagramAPIClient,
    GoogleNewsClient,
    AppleNewsClient,
    MicrosoftStartClient,
    create_platform_integrator,
    create_search_engine_integrator,
    create_social_posting_queue,
    create_platform_api_integrator,
    create_optional_platform_integrator,
    create_example_config
)
from .cdn_manager import (
    CDNManager,
    EnhancedCDNManager,
    CacheConfigurationSystem,
    CacheHeaderGenerator,
    ContentCompressor,
    AssetOptimizer,
    AssetBundler,
    CacheInvalidationSystem,
    PerformanceMonitor,
    CDNProviderInterface,
    CloudflareCDNProvider,
    CacheType,
    CacheConfig,
    CompressionType,
    CompressionConfig,
    CacheHeaders,
    OptimizedAsset,
    InvalidationType,
    InvalidationRequest,
    InvalidationResult,
    CacheWarmingRequest,
    CacheWarmingResult,
    PerformanceMetrics,
    ETagGenerator,
    LastModifiedGenerator,
    create_cdn_manager,
    create_enhanced_cdn_manager,
    create_cache_configuration_system,
    create_cache_header_generator,
    create_compression_config,
    create_content_compressor,
    create_asset_optimizer,
    create_asset_bundler,
    create_cloudflare_cdn_provider,
    create_cache_invalidation_system
)
# from .feed_validator import (
#     RSSFeedValidator,
#     XMLSitemapValidator,
#     SocialPackageValidator,
#     ValidationAggregator,
#     FeedValidationReport,
#     SocialPackageValidationReport,
#     create_feed_validators,
#     create_social_package_validator
# )

__all__ = [
    'PipelineOrchestrator',
    'ConfigurationManager', 
    'setup_logging',
    'get_logger',
    'PipelineError',
    'ConfigurationError',
    'ProcessingError',
    'ValidationError',
    'TransientError',
    'MediaPreparationEngine',
    'MediaValidator',
    'MediaHealthChecker',
    'MediaPreparationPipeline',
    'AudioFile',
    'ValidationResult',
    'ClipObject',
    'ClipAsset',
    'ClipStatus',
    'ClipRegistry',
    'FeedGenerator',
    'RSSFeed',
    'XMLSitemap',
    'FeedCache',
    'create_feed_generator',
    'validate_feed_xml',
    'PlatformProfile',
    'PlatformProfileLoader',
    'MediaSpecValidator',
    'VideoSpecs',
    'AudioSpecs',
    'MetadataSpecs',
    'create_default_profiles_config',
    'save_default_profiles_config',
    'MediaNormalizationPipeline',
    'VideoTranscoder',
    'AudioNormalizer',
    'ThumbnailGenerator',
    'CaptionProcessor',
    'MediaProber',
    'NormalizationJob',
    'NormalizationResult',
    'create_normalization_pipeline',
    'SocialGenerator',
    'PlatformMetadataFormatter',
    'SocialPackageValidator',
    'SocialGenerationJob',
    'SocialGenerationResult',
    'create_social_generator',
    'SocialQueueManager',
    'SocialQueue',
    'QueueItem',
    'QueueItemStatus',
    'SchedulingStrategy',
    'SchedulingConfig',
    'create_social_queue_manager',
    'create_scheduling_config',
    'ComplianceValidator',
    'RightsValidator',
    'ContentPolicyValidator',
    'AccessibilityValidator',
    'ComplianceReport',
    'ComplianceViolation',
    'ContentPolicyRule',
    'ContentRating',
    'ComplianceLevel',
    'create_compliance_validator',
    'DeploymentPipeline',
    'StagingDeployment',
    'ProductionDeployment',
    'ValidationGateSystem',
    'DeploymentConfig',
    'DeploymentResult',
    'DeploymentStatus',
    'Environment',
    'ValidationGateType',
    'ValidationGateResult',
    'ValidationReport',
    'DeploymentHistory',
    'ContentCounts',
    'create_deployment_pipeline',
    'create_staging_deployment',
    'create_production_deployment',
    'create_validation_gate_system',
    'create_zero_tolerance_config',
    'create_lenient_config',
    'validate_deployment_config',
    'PlatformIntegrator',
    'SearchEngineIntegrator',
    'SocialPostingQueue',
    'PlatformAPIIntegrator',
    'OptionalPlatformIntegrator',
    'PlatformCredentials',
    'SubmissionResult',
    'VerificationResult',
    'QueueItem',
    'PostingReceipt',
    'QueueResult',
    'PostResult',
    'PlatformType',
    'SubmissionStatus',
    'ErrorClassification',
    'GoogleSearchConsoleClient',
    'BingWebmasterToolsClient',
    'YouTubeAPIClient',
    'InstagramAPIClient',
    'GoogleNewsClient',
    'AppleNewsClient',
    'MicrosoftStartClient',
    'create_platform_integrator',
    'create_search_engine_integrator',
    'create_social_posting_queue',
    'create_platform_api_integrator',
    'create_optional_platform_integrator',
    'create_example_config',
    'CDNManager',
    'EnhancedCDNManager',
    'CacheConfigurationSystem',
    'CacheHeaderGenerator',
    'ContentCompressor',
    'AssetOptimizer',
    'AssetBundler',
    'CacheInvalidationSystem',
    'PerformanceMonitor',
    'CDNProviderInterface',
    'CloudflareCDNProvider',
    'CacheType',
    'CacheConfig',
    'CompressionType',
    'CompressionConfig',
    'CacheHeaders',
    'OptimizedAsset',
    'InvalidationType',
    'InvalidationRequest',
    'InvalidationResult',
    'CacheWarmingRequest',
    'CacheWarmingResult',
    'PerformanceMetrics',
    'ETagGenerator',
    'LastModifiedGenerator',
    'create_cdn_manager',
    'create_enhanced_cdn_manager',
    'create_cache_configuration_system',
    'create_cache_header_generator',
    'create_compression_config',
    'create_content_compressor',
    'create_asset_optimizer',
    'create_asset_bundler',
    'create_cloudflare_cdn_provider',
    'create_cache_invalidation_system',
    'PublishingSystem',
    'PublishingConfig',
    'WorkflowResult',
    'WorkflowStage',
    'create_publishing_system',
    'create_default_config',
    'load_config_from_file',
    'ConfigurationManager',
    'Environment',
    'FeatureFlag',
    'EnvironmentConfig',
    'IntegrationConfig',
    'SecretConfig',
    'create_configuration_manager',
    'create_default_environment_configs',
    'setup_default_config_files',
    'WorkflowOrchestrator',
    'WorkflowPhase',
    'WorkflowMetrics',
    'WorkflowReport',
    'create_workflow_orchestrator',
    'create_workflow_orchestrator_from_config'
    # 'RSSFeedValidator',
    # 'XMLSitemapValidator',
    # 'SocialPackageValidator',
    # 'ValidationAggregator',
    # 'FeedValidationReport',
    # 'SocialPackageValidationReport',
    # 'create_feed_validators',
    # 'create_social_package_validator'
]